# Site settings
title: Officer 2 Engineer
email: jsjones96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The journey of a naval officer to software engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonsjones.github.io" # the base hostname & protocol for your site
twitter_username: jsj0nes
github_username:  jasonsjones

# Build settings
markdown: kramdown
